#!/usr/bin/env bash
# Link gale-harness, compound-plugin, gale-knowledge, and gale-memory to local source tree for development.
# Creates wrapper scripts that invoke `bun run` on the source, so the commands
# work the same as the release symlinks (which point to .ts with #!/usr/bin/env bun).
# Run from repo root or pass the repo path as $1.
set -euo pipefail

REPO_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
BIN_DIR="$HOME/.bun/bin"
DEFAULT_ENTRY="$REPO_ROOT/src/index.ts"

if [ ! -f "$DEFAULT_ENTRY" ]; then
  echo "ERROR: $DEFAULT_ENTRY not found. Are you in the GaleHarnessCodingCLI repo?"
  exit 1
fi

for bin in gale-harness compound-plugin gale-knowledge gale-memory; do
  # Select entry file per binary
  if [ "$bin" = "gale-knowledge" ]; then
    ENTRY="$REPO_ROOT/cmd/gale-knowledge/index.ts"
  elif [ "$bin" = "gale-memory" ]; then
    ENTRY="$REPO_ROOT/cmd/gale-memory/index.ts"
  else
    ENTRY="$DEFAULT_ENTRY"
  fi
  LINK="$BIN_DIR/$bin"
  # Save current symlink target so dev-unlink can restore it
  BACKUP="$BIN_DIR/${bin}.release-target"
  if [ -L "$LINK" ]; then
    current_target="$(readlink "$LINK")"
    echo "$current_target" > "$BACKUP"
    echo "Saved release target: $current_target"
  elif [ -f "$LINK" ]; then
    # Dev wrapper from a previous dev-link — overwrite below
    :
  fi
  # Remove existing link/file so we can write a wrapper
  rm -f "$LINK"
  cat > "$LINK" <<WRAPPER
#!/usr/bin/env bun
// Dev wrapper — auto-generated by scripts/dev-link.sh
import "$ENTRY"
WRAPPER
  chmod +x "$LINK"
  echo "Linked $bin -> wrapper -> $ENTRY"
done

echo ""
echo "Dev mode active. Run 'bash scripts/dev-unlink.sh' to restore."
